---
title: "MATH 3190 Homework 3"
author: "Data Visualizations and Ethics"
date: "Due 3/9/2022"
output: pdf_document
---

Here is 

\begin{enumerate}
	\item (get your previous points!) Keep working on your Shiny interfaces and packages! Complete any of the previous tasks you have not finished, and work to make your packages and interfaces better!
	\item (20 points) Using the principles and guidelines from the data visualization lecture slides (we did not finish!), evaluate the plots in your Shiny interfaces (k means and basketball) and improve them! Also, add 3 more high-quality and highly-informative plots or tables to your interface. Use ggplot for all plots in the interface!
	\item (20 points) Finish going through the examples from the ggplot lecture. Confirm in your RMarkdown that you completed this task (on your honor!).  
	\begin{enumerate}
    	    \item [$\bullet$] Done! Code added to homework 3 folder 
  \end{enumerate}
	\item (20 points) Go find 5 solid examples where statistics have been misused, misrepresented (graphs), or misinterpreted. Add the link or graph to the RMarkdown document, and describe what they did wrong. What should they have done differently? Which of the 12 data science principles did they violate?  
	 
\end{enumerate}

